name: OSRS Revision Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0/30 * * * *

jobs:
  revision-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Get revision
        run: |
          revisionOutput=$(java -jar target/gamepack-hosting-1.0-SNAPSHOT-jar-with-dependencies.jar --revision)
          revision=$(echo "$revisionOutput" | grep -oP '^\d{3}(\.\d)?')
          echo "Revision: $revision"

          if [[ -z "$revision" || ! "$revision" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
              echo "Revision is invalid!"
              exit 1
          fi

          echo "REVISION=$revision" >> $GITHUB_ENV

      - name: Download gamepack
        run: |
          mkdir -p net/runelite/rs/vanila/$REVISION/
          java -jar target/gamepack-hosting-1.0-SNAPSHOT-jar-with-dependencies.jar --save net/runelite/rs/vanilla/$REVISION/vanilla-$REVISION.jar --pom net/runelite/rs/vanilla/$REVISION/vanilla-$REVISION.pom --groupId net.runelite.rs --artifactId vanilla --version $REVISION

      - name: Push to github
        run: |
          git config --global user.email "adrian989@me.com"
          git config --global user.name "AdrianFred"
          git add .

          if ! git diff --cached --quiet; then
            modified_files=$(git diff --cached --name-only)
            jar_changed=$(echo "$modified_files" | grep -E '\.jar$')

            if [ -n "$jar_changed" ]; then
              git commit -m "release - $REVISION"
              git push https://AdrianFred:${{secrets.REPO_PAT}}@github.com/AdrianFred/osrs-gamepack-hosting.git main
            else
              echo ".jar file must be changed to commit."
            fi
          else
            echo "No changes to commit."
          fi
